# Generated by Django 4.1 on 2022-09-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Char',
            new_name='Chat',
        ),
    ]
