# Generated by Django 4.1 on 2022-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('direcrtor', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
