# Generated by Django 4.1 on 2022-09-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='direcrtor',
            new_name='director',
        ),
    ]
